from __future__ import annotations

from typing import Any

from app.schemas.common import ApiError, ApiResponse


INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
FILE_TOO_LARGE = "FILE_TOO_LARGE"
DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
DOCUMENT_UPLOAD_FAILED = "DOCUMENT_UPLOAD_FAILED"
MINIO_BUCKET_NOT_FOUND = "MINIO_BUCKET_NOT_FOUND"
MINIO_SERVICE_UNAVAILABLE = "MINIO_SERVICE_UNAVAILABLE"
DOCUMENT_ALREADY_PARSED = "DOCUMENT_ALREADY_PARSED"
DOCUMENT_PARSE_FAILED = "DOCUMENT_PARSE_FAILED"
DOCUMENT_PARSER_UNAVAILABLE = "DOCUMENT_PARSER_UNAVAILABLE"
DOCUMENT_SOURCE_FILE_NOT_FOUND = "DOCUMENT_SOURCE_FILE_NOT_FOUND"
DOCUMENT_CHUNK_CONFIG_INVALID = "DOCUMENT_CHUNK_CONFIG_INVALID"
DOCUMENT_NOT_PARSED = "DOCUMENT_NOT_PARSED"
DOCUMENT_EMBEDDINGS_ALREADY_GENERATED = "DOCUMENT_EMBEDDINGS_ALREADY_GENERATED"
EMBEDDING_CONFIG_INVALID = "EMBEDDING_CONFIG_INVALID"
EMBEDDING_MODEL_PATH_NOT_FOUND = "EMBEDDING_MODEL_PATH_NOT_FOUND"
EMBEDDING_DEPENDENCY_MISSING = "EMBEDDING_DEPENDENCY_MISSING"
EMBEDDING_MODEL_LOAD_FAILED = "EMBEDDING_MODEL_LOAD_FAILED"
EMBEDDING_DIMENSION_MISMATCH = "EMBEDDING_DIMENSION_MISMATCH"
EMBEDDING_GENERATION_FAILED = "EMBEDDING_GENERATION_FAILED"
VECTOR_SEARCH_FAILED = "VECTOR_SEARCH_FAILED"
NO_EMBEDDED_CHUNKS = "NO_EMBEDDED_CHUNKS"
SEARCH_ENGINE_CONFIG_INVALID = "SEARCH_ENGINE_CONFIG_INVALID"
SEARCH_ENGINE_UNAVAILABLE = "SEARCH_ENGINE_UNAVAILABLE"
SEARCH_INDEX_NOT_FOUND = "SEARCH_INDEX_NOT_FOUND"
SEARCH_INDEX_EMPTY = "SEARCH_INDEX_EMPTY"
SEARCH_INDEX_CREATE_FAILED = "SEARCH_INDEX_CREATE_FAILED"
SEARCH_INDEX_REBUILD_FAILED = "SEARCH_INDEX_REBUILD_FAILED"
SEARCH_INDEX_MAPPING_MISMATCH = "SEARCH_INDEX_MAPPING_MISMATCH"
HYBRID_SEARCH_FAILED = "HYBRID_SEARCH_FAILED"
HYBRID_SEARCH_CONFIG_INVALID = "HYBRID_SEARCH_CONFIG_INVALID"
SEARCH_QUERY_EMPTY = "SEARCH_QUERY_EMPTY"


class BusinessError(Exception):
    def __init__(
        self,
        code: str,
        message: str,
        *,
        detail: Any | None = None,
        status_code: int = 400,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.detail = detail
        self.status_code = status_code

    def to_api_error(self) -> ApiError:
        return ApiError(code=self.code, message=self.message, detail=self.detail)


def error_response(error: BusinessError) -> ApiResponse[None]:
    return ApiResponse[None](success=False, data=None, error=error.to_api_error())
